// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	comment "simple-social-media-API/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, newComment
func (_m *CommentService) Add(token interface{}, newComment comment.Core) (comment.Core, error) {
	ret := _m.Called(token, newComment)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(interface{}, comment.Core) comment.Core); ok {
		r0 = rf(token, newComment)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, comment.Core) error); ok {
		r1 = rf(token, newComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, commentId
func (_m *CommentService) Delete(token interface{}, commentId uint) error {
	ret := _m.Called(token, commentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, commentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: token, commentId, postId, updComment
func (_m *CommentService) Update(token interface{}, commentId uint, postId uint, updComment comment.Core) (comment.Core, error) {
	ret := _m.Called(token, commentId, postId, updComment)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, uint, comment.Core) comment.Core); ok {
		r0 = rf(token, commentId, postId, updComment)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, uint, comment.Core) error); ok {
		r1 = rf(token, commentId, postId, updComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentService creates a new instance of CommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentService(t mockConstructorTestingTNewCommentService) *CommentService {
	mock := &CommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
