name: remote ssh command
on:
  push:
    branches: 
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/socmedproject:latest
    - 
      name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop socmedproject
          docker rm socmedproject
          docker rmi ${{ secrets.DOCKER_USER }}/socmedproject:latest
          docker pull ${{ secrets.DOCKER_USER }}/socmedproject:latest
          docker run --name socmedproject -d -e DBUSER=admin -e DBPASS=${{ secrets.DBPASS_RDS_SOCMEDDB }} -e DBHOST=projectsocmeddb.cssizdymws4b.ap-southeast-1.rds.amazonaws.com -e DBPORT=3306 -e DBNAME=socmedDB -e JWT_KEY="BEa|t3rr4" -e KEYID=${{ secrets.S3_KEYID }} -e ACCESSKEY=${{ secrets.S3_ACCESSKEY }} -p 80:8000 mfauzanptra/socmedproject
